### ISSUE TITLE
Posting Emojis leads to InvalidArgumentException

### ISSUE THREAD

**Issue by spharion88** [engram-design/SocialPoster#27]
### Description
Posting an Emoji to Facebook works, but leads to an InvalidArgumentException after loading the page again in the craft backend

```
2019-09-19 00:31:09 [-][1][f46054f7f66292f0e6a68bfc1dcf1394][error][yii\base\InvalidArgumentException] yii\base\InvalidArgumentException: Control character error, possibly incorrectly encoded. in /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/helpers/BaseJson.php:133
Stack trace:
#0 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/helpers/BaseJson.php(107): yii\helpers\BaseJson::handleJsonError(3)
#1 /Users/phillip/Documents/Projekte/voitl-website/vendor/verbb/social-poster/src/elements/Post.php(121): yii\helpers\BaseJson::decode('{"endpoint":"pa...', true)
#2 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/base/BaseObject.php(109): verbb\socialposter\elements\Post->init()
#3 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2306): yii\base\BaseObject->__construct(Array)
#4 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/elements/db/ElementQuery.php(2227): craft\elements\db\ElementQuery->_createElement(Array)
#5 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1176): craft\elements\db\ElementQuery->_createElements(Array)
#6 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/db/Query.php(238): craft\elements\db\ElementQuery->populate(Array)
#7 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/db/Query.php(161): yii\db\Query->all(NULL)
#8 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1205): craft\db\Query->all(NULL)
#9 /Users/phillip/Documents/Projekte/voitl-website/vendor/verbb/social-poster/src/services/Service.php(68): craft\elements\db\ElementQuery->all()
#10 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/View.php(1270): verbb\socialposter\services\Service->renderEntrySidebar('<span class="st...')
#11 /Users/phillip/Documents/Projekte/voitl-website/storage/runtime/compiled_templates/b8/b82da87eddb747876562e830f3e22a11bd49c0c8e82c0bcad14a569ecabd81bd.php(637): craft\web\View->invokeHook('cp.entries.edit...', '<span class="st...')
#12 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(184): __TwigTemplate_c30bc86737448f23f140cab523d3118475fb8b3c731ee84335e8a323a1b2a9f4->block_details('<span class="st...', Array)
#13 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(248): Twig\Template->displayBlock('details', Array, Array, true)
#14 /Users/phillip/Documents/Projekte/voitl-website/storage/runtime/compiled_templates/67/670068945e4dd939ed6e8413de34d83cd59fb8e35183fc6082453bd7835044fa.php(93): Twig\Template->renderBlock('details', Array, Array)
#15 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(382): __TwigTemplate_a717e6ede0f87d7d4b430f12572ad7b9e221d8d67c0f8bdc63ad5f0a03410653->doDisplay(Array, Array)
#16 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#18 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#19 /Users/phillip/Documents/Projekte/voitl-website/storage/runtime/compiled_templates/b8/b82da87eddb747876562e830f3e22a11bd49c0c8e82c0bcad14a569ecabd81bd.php(79): craft\web\twig\Template->display(Array, Array)
#20 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(382): __TwigTemplate_c30bc86737448f23f140cab523d3118475fb8b3c731ee84335e8a323a1b2a9f4->doDisplay('[<span class="s...', Array)
#21 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/twig/Template.php(52): Twig\Template->displayWithErrorHandling(Array, Array)
#22 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(359): craft\web\twig\Template->displayWithErrorHandling(Array, Array)
#23 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/twig/Template.php(34): Twig\Template->display(Array, Array)
#24 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Template.php(367): craft\web\twig\Template->display(Array)
#25 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#26 /Users/phillip/Documents/Projekte/voitl-website/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#27 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/View.php(343): Twig\Environment->render('entries/_edit', Array)
#28 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('entries/_edit', '[<span class="s...')
#29 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/Controller.php(161): craft\web\View->renderPageTemplate('entries/_edit', '[<span class="s...')
#30 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/controllers/EntriesController.php(383): craft\web\Controller->renderTemplate('entries/_edit', Array)
#31 [internal function]: craft\controllers\EntriesController->actionEditEntry('pages', 6, NULL, NULL, 'default', Object(craft\elements\Entry))
#32 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#33 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#34 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/Controller.php(109): yii\base\Controller->runAction('edit-entry', Array)
#35 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('edit-entry', Array)
#36 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/Application.php(297): yii\base\Module->runAction('entries/edit-en...', Array)
#37 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('entries/edit-en...', Array)
#38 /Users/phillip/Documents/Projekte/voitl-website/vendor/craftcms/cms/src/web/Application.php(286): yii\web\Application->handleRequest(Object(craft\web\Request))
#39 /Users/phillip/Documents/Projekte/voitl-website/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#40 /Users/phillip/Documents/Projekte/voitl-website/web/index.php(21): yii\base\Application->run()
#41 {main}
```

Adding a try/catch block is definitively not the nicest solution, but it would solve the problem:
```php
try {
    $this->settings = Json::decode($this->settings, true);
} catch (\yii\base\InvalidArgumentException $e) {
    $this->settings = [];
}
```

### Steps to reproduce

1. Post any Emoji to Facebook
2. Load the page again in Craft Backend

### Additional info

- Plugin version: 2.0.8
- Craft version: 3.1.24

**Comment by engram-design** [comment]
Added in [2.0.9](https://github.com/verbb/social-poster/releases/tag/2.0.9)

**Comment by bymayo** [comment]
Seem to be having an issue with emojis again:

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x93\xA3 N...' for column `melted_hartebeest_production`.`socialposter_accounts`.`settings` at row 1
The SQL being executed was: UPDATE `socialposter_accounts` SET `settings`='{\"showMessage\":\"1\",\"message\":\"📣 New tool added — {title}\\r\\n{entry.url}\"}', `dateUpdated`='2022-01-12 12:18:50' WHERE `id`=4
```

**Comment by engram-design** [comment]
@bymayo Emoji's weren't supported in the account settings, but they are in [2.3.2](https://github.com/verbb/social-poster/releases/tag/2.3.2)

**Comment by bymayo** [comment]
@engram-design Thanks for the speedy response and fix!

**Comment by mijewe** [comment]
I'm still having this issue in 4.0.1 - though slightly different.

Setting my Account's Post message saves fine. And the Tweet actually gets tweeted. But when Social Poster tries to save the Post data into the database it throws an Exception like the one above.

Although mine is failing when saving into `socialposter_posts` rather than `socialposter_accounts`.

```
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x91\x89 h...' for column `db`.`socialposter_posts`.`data` at row 1
```

during
```
$elementsService->saveElement($post))
```

over in the Service service.

**Comment by engram-design** [comment]
Updated for the next release. To get this early, run `composer require verbb/social-poster:"dev-craft-4 as 4.0.1"`.
