### ISSUE TITLE
Uninstalling the plugin throws an error in Craft 5

### ISSUE THREAD

**Issue by benfeather** [engram-design/SocialPoster#50]
### Describe the bug

I was uninstalling all of my plugins to report a bug in Craft Commerce and noticed this one throws an error:

```
Error: Call to a member function getTokens() on null in /var/www/html/vendor/verbb/social-poster/src/migrations/Install.php:33
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(82): verbb\socialposter\migrations\Install->safeDown()
#1 /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php(294): craft\db\Migration->down(true)
#2 /var/www/html/vendor/craftcms/cms/src/base/Plugin.php(165): craft\db\MigrationManager->migrateDown(Object(verbb\socialposter\migrations\Install))
#3 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(621): craft\base\Plugin->uninstall()
#4 /var/www/html/vendor/craftcms/cms/src/controllers/PluginsController.php(83): craft\services\Plugins->uninstallPlugin('social-poster')
#5 [internal function]: craft\controllers\PluginsController->actionUninstallPlugin()
#6 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('uninstall-plugi...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('plugins/uninsta...', Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction('plugins/uninsta...', Array)
#11 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /var/www/html/web/index.php(17): yii\base\Application->run()
#14 {main}

Next craft\errors\MigrationException: An error occurred while executing the "verbb\socialposter\migrations\Install migration: Call to a member function getTokens() on null in /var/www/html/vendor/craftcms/cms/src/db/MigrationManager.php:314
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/base/Plugin.php(165): craft\db\MigrationManager->migrateDown(Object(verbb\socialposter\migrations\Install))
#1 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(621): craft\base\Plugin->uninstall()
#2 /var/www/html/vendor/craftcms/cms/src/controllers/PluginsController.php(83): craft\services\Plugins->uninstallPlugin('social-poster')
#3 [internal function]: craft\controllers\PluginsController->actionUninstallPlugin()
#4 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('uninstall-plugi...', Array)
#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\base\Module->runAction('plugins/uninsta...', Array)
#8 /var/www/html/vendor/craftcms/cms/src/web/Application.php(650): craft\web\Application->runAction('plugins/uninsta...', Array)
#9 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#10 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#11 /var/www/html/web/index.php(17): yii\base\Application->run()
#12 {main}
```

P.S. I'm sorry I keep breaking things 🥲

### Steps to reproduce

1. Install the plugin through the plugin store
2. Go to Settings > Plugins
3. Uninstall "Social poster"

### Craft CMS version

5.0.0-beta.6

### Plugin version

5.0.0-beta.1

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/social-poster:"dev-craft-5 as 5.0.0-beta.1"`

**Comment by benfeather** [comment]
Fixed, thank you!
